Fix build: boost::shared_*_cast are deprecated, removed in boost 1.53
Compiling fails on systems with boost 1.53 and you'll get an error like the one
pasted below.

connection.hpp has a boost::shared_dynamic_cast() function call
but this function was deprecated as long ago as boost 1.35 (search for
deprecated in http://www.boost.org/doc/libs/1_35_0/boost/shared_ptr.hpp)
and has been removed in boost 1.53 (latest version). The recommend
instead to use boost::dynamic_pointer_cast().

[  168s] /home/abuild/rpmbuild/BUILD/nscp/include/socket/connection.hpp: In member function 'virtual void socket_helpers::server::ssl_connectiorotocol_type, N>::start()':
[  168s] /home/abuild/rpmbuild/BUILD/nscp/include/socket/connection.hpp:227:39: error: 'shared_dynamic_cast' is not a member of 'boost'
[  168s]      boost::shared_ptr<my_type> self = boost::shared_dynamic_cast<my_type>(this->shared_from_this());
[  168s]                                        ^
[  168s]
/home/abuild/rpmbuild/BUILD/nscp/include/socket/connection.hpp:227:73: error: expected primary-expression before '>' token
[  168s]      boost::shared_ptr<my_type> self = boost::shared_dynamic_cast<my_type>(this->shared_from_this());
[  168s]
[  168s] [ 59%] Building CXX object modules/SimpleCache/CMakeFiles/SimpleCache.dir/stdafx.cpp.o
[  169s] make[2]: ***
[modules/CheckMKServer/CMakeFiles/CheckMKServer.dir/module.cpp.o] Error
1
[  169s] make[1]: ***
[modules/CheckMKServer/CMakeFiles/CheckMKServer.dir/all] Error 2