docs/conf.py - pdf_use_index set to False
Had to change pdf_use_index to False because otherwise
nscp would not build for me using rst2pdf-0.16-2

This was the error i was getting before:

[ERROR] pdfbuilder.py:130 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rst2pdf/pdfbuilder.py", line 122, in write
    appendices=opts.get('pdf_appendices', self.config.pdf_appendices) or [])
  File "/usr/lib/pymodules/python2.7/rst2pdf/pdfbuilder.py", line 219, in assemble_doctree
    index_nodes=genindex_nodes(genindex)
  File "/usr/lib/pymodules/python2.7/rst2pdf/pdfbuilder.py", line 398, in genindex_nodes
    output.append('`%s <#%s>`_'%(entryname,nodes.make_id(links[0])))
  File "/usr/lib/python2.7/dist-packages/docutils/nodes.py", line 1838, in make_id
    id = string.lower()
AttributeError: 'tuple' object has no attribute 'lower'
[100%] Built target build_docs_pdf